settings:
  title: 'status'
  url: '' # used for Slack messages
  logo: favicon.svg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'No Response'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'Response'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: milankomaj-934e3
    name: milankomaj
    url: 'https://milankomaj-934e3.firebaseapp.com'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    description: 'milankomaj-934e3.firebaseapp.com' # default=empty

  - id: radio-fm
    name: radio fm
    description: 'mp3/128/https'
    url: 'https://icecast.stv.livebox.sk/fm_128.mp3'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-regina
    name: radio regina
    description: 'mp3/128/https'
    url: 'https://icecast.stv.livebox.sk/regina-bb_128.mp3'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-fun
    name: fun radio
    description: 'mp3/128/https'
    url: 'https://stream.funradio.sk:18443/fun128.mp3'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-europa
    name: europa 2
    description: 'mp3/128/https'
    url: 'https://stream.bauermedia.sk/europa2.mp3'
    method: HEAD
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-jemne
    name: radio melody
    description: 'mp3/128/https'
    url: 'https://stream.bauermedia.sk/melody-hi.mp3'
    method: HEAD
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-rock
    name: radio rock
    description: 'mp3/128/https'
    url: 'https://stream.bauermedia.sk/rock-hi.mp3'
    method: HEAD
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-slovensko
    name: radio slovensko
    description: 'mp3/128/https'
    url: 'https://icecast.stv.livebox.sk/slovensko_128.mp3'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-expres
    name: radio expres
    description: 'mp3/128/https'
    url: 'https://stream.expres.sk/128.mp3'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-kiks
    name: radio kiks
    description: 'radioserver/https'
    url: 'https://online.radiokiks.sk:8000'
    method: GET
    expectStatus: 302
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-vlna
    name: radio vlna
    description: 'mp3/128/https'
    url: 'https://stream.radiovlna.sk/vlna-hi.mp3'
    method: HEAD
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-wow
    name: radio wow
    description: 'radioserver/https'
    url: 'https://radioserver.online:9816'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false # allows the title to be a link, default=true

  - id: bb-fm
    name: bb fm
    description: 'radioserver/https'
    url: 'https://stream.bbfm.sk:18443'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-best
    name: best fm
    description: 'radioserver/https'
    url: 'https://stream3.bestfm.sk:8000/128.mp3'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true

  - id: radio-kosice
    name: rádio košice
    description: 'mp3/128/https'
    url: 'https://stream.21.sk/radiokosice-128.mp3'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false # allows the title to be a link, default=true
