name = "status"
workers_dev = true
account_id = ""
compatibility_date = "2021-09-18"
main = "index.js"
kv_namespaces = [{binding="KV_STATUS_PAGE", id="f0d41ec3d6f545188d33f201fd6680a7", preview_id="f0d41ec3d6f545188d33f201fd6680a7"}]

[triggers]
crons = ["*/10 * * * *"]

[site]
bucket = "out"


# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"

