export const locations = {
    ADL: 'Adelaide, SA, Australia',
    AKL: 'Auckland, New Zealand',
    AMM: 'Amman, Jordan',
    AMS: 'Amsterdam, Netherlands',
    ARI: 'Arica, Chile',
    ARN: 'Stockholm, Sweden',
    ASU: 'Asunción, Paraguay',
    ATH: 'Athens, Greece',
    ATL: 'Atlanta, GA, United States',
    BAH: 'Manama, Bahrain',
    BCN: 'Barcelona, Spain',
    BEG: 'Belgrade, Serbia',
    BEY: 'Beirut, Lebanon',
    BGW: 'Baghdad, Iraq',
    BKK: 'Bangkok, Thailand',
    BLR: 'Bangalore, India',
    BNA: 'Nashville, TN, United States',
    BNE: 'Brisbane, QLD, Australia',
    BOG: 'Bogotá, Colombia',
    BOM: 'Mumbai, India',
    BOS: 'Boston, MA, United States',
    BRU: 'Brussels, Belgium',
    BUD: 'Budapest, Hungary',
    BUF: 'Buffalo, NY, United States',
    BWN: 'Bandar Seri Begawan, Brunei',
    BYOIP: 'Bring Your Own IP',
    CAN: 'Guangzhou, China',
    CCU: 'Kolkata, India',
    CDG: 'Paris, France',
    CEB: 'Cebu, Philippines',
    CGK: 'Jakarta, Indonesia',
    CGO: 'Zhengzhou, China',
    CGP: 'Chittagong, Bangladesh',
    CKG: 'Chongqing, China',
    CLT: 'Charlotte, NC, United States',
    CMB: 'Colombo, Sri Lanka',
    CMH: 'Columbus, OH, United States',
    CMN: 'Casablanca, Morocco',
    CPH: 'Copenhagen, Denmark',
    CPT: 'Cape Town, South Africa',
    CSX: 'Zhuzhou, China',
    CTU: 'Chengdu, China',
    CUR: 'Willemstad, Curaçao',
    CWB: 'Curitiba, Brazil',
    DAC: 'Dhaka, Bangladesh',
    DAR: 'Dar Es Salaam, Tanzania',
    DEL: 'New Delhi, India',
    DEN: 'Denver, CO, United States',
    DFW: 'Dallas, TX, United States',
    DKR: 'Dakar, Senegal',
    DME: 'Moscow, Russia',
    DOH: 'Doha, Qatar',
    DTW: 'Detroit, MI, United States',
    DUB: 'Dublin, Ireland',
    DUR: 'Durban, South Africa',
    DUS: 'Düsseldorf, Germany',
    DXB: 'Dubai, United Arab Emirates',
    EDI: 'Edinburgh, United Kingdom',
    EVN: 'Yerevan, Armenia',
    EWR: 'Newark, NJ, United States',
    EZE: 'Buenos Aires, Argentina',
    FCO: 'Rome, Italy',
    FOC: 'Fuzhou, China',
    FOR: 'Fortaleza, Brazil',
    FRA: 'Frankfurt, Germany',
    FUO: 'Foshan, China',
    GIG: 'Rio de Janeiro, Brazil',
    GND: 'St. George, Grenada',
    GOT: 'Gothenburg, Sweden',
    GRU: 'São Paulo, Brazil',
    GUA: 'Guatemala City, Guatemala',
    GVA: 'Geneva, Switzerland',
    GYD: 'Baku, Azerbaijan',
    HAM: 'Hamburg, Germany',
    HAN: 'Hanoi, Vietnam',
    HEL: 'Helsinki, Finland',
    HGH: 'Hangzhou, China',
    HKG: 'Hong Kong',
    HNL: 'Honolulu, HI, United States',
    HNY: 'Hengyang, China',
    HYD: 'Hyderabad, India',
    IAD: 'Ashburn, VA, United States',
    IAH: 'Houston, TX, United States',
    ICN: 'Seoul, South Korea',
    IND: 'Indianapolis, IN, United States',
    ISB: 'Islamabad, Pakistan',
    IST: 'Istanbul, Turkey',
    JAX: 'Jacksonville, FL, United States',
    JHB: 'Johor Bahru, Malaysia',
    JIB: 'Djibouti City, Djibouti',
    JNB: 'Johannesburg, South Africa',
    JSR: 'Jashore, Bangladesh',
    KBP: 'Kyiv, Ukraine',
    KEF: 'Reykjavík, Iceland',
    KGL: 'Kigali, Rwanda',
    KHI: 'Karachi, Pakistan',
    KIV: 'Chișinău, Moldova',
    KIX: 'Osaka, Japan',
    KTM: 'Kathmandu, Nepal',
    KUL: 'Kuala Lumpur, Malaysia',
    KWI: 'Kuwait City, Kuwait',
    LAD: 'Luanda, Angola',
    LAS: 'Las Vegas, NV, United States',
    LAX: 'Los Angeles, CA, United States',
    LCA: 'Nicosia, Cyprus',
    LED: 'Saint Petersburg, Russia',
    LHE: 'Lahore, Pakistan',
    LHR: 'London, United Kingdom',
    LIM: 'Lima, Peru',
    LIS: 'Lisbon, Portugal',
    LOS: 'Lagos, Nigeria',
    LUX: 'Luxembourg City, Luxembourg',
    LYA: 'Luoyang, China',
    MAA: 'Chennai, India',
    MAD: 'Madrid, Spain',
    MAN: 'Manchester, United Kingdom',
    MBA: 'Mombasa, Kenya',
    MCI: 'Kansas City, MO, United States',
    MCT: 'Muscat, Oman',
    MDE: 'Medellín, Colombia',
    MEL: 'Melbourne, VIC, Australia',
    MEM: 'Memphis, TN, United States',
    MEX: 'Mexico City, Mexico',
    MFE: 'McAllen, TX, United States',
    MFM: 'Macau',
    MGM: 'Montgomery, AL, United States',
    MIA: 'Miami, FL, United States',
    MLE: 'Malé, Maldives',
    MNL: 'Manila, Philippines',
    MPM: 'Maputo, MZ',
    MRS: 'Marseille, France',
    MRU: 'Port Louis, Mauritius',
    MSP: 'Minneapolis, MN, United States',
    MUC: 'Munich, Germany',
    MXP: 'Milan, Italy',
    NAG: 'Nagpur, India',
    NAY: 'Langfang, China',
    NBG: 'Ningbo, China',
    NBO: 'Nairobi, Kenya',
    NOU: 'Noumea, New Caledonia',
    NRT: 'Tokyo, Japan',
    OMA: 'Omaha, NE, United States',
    ORD: 'Chicago, IL, United States',
    ORF: 'Norfolk, VA, United States',
    ORK: 'Cork, Ireland',
    OSL: 'Oslo, Norway',
    OTP: 'Bucharest, Romania',
    PAP: 'Port-Au-Prince, Haiti',
    PBH: 'Thimphu, Bhutan',
    PBM: 'Paramaribo, Suriname',
    PDX: 'Portland, OR, United States',
    PER: 'Perth, WA, Australia',
    PHL: 'Philadelphia, United States',
    PHX: 'Phoenix, AZ, United States',
    PIT: 'Pittsburgh, PA, United States',
    PNH: 'Phnom Penh, Cambodia',
    POA: 'Porto Alegre, Brazil',
    PRG: 'Prague, Czech Republic',
    PTY: 'Panama City, Panama',
    QRO: 'Queretaro, MX, Mexico',
    RGN: 'Yangon, Myanmar',
    RIC: 'Richmond, VA, United States',
    RIX: 'Riga, Latvia',
    ROB: 'Monrovia, Liberia',
    RUH: 'Riyadh, Saudi Arabia',
    RUN: 'Réunion, France',
    SAN: 'San Diego, CA, United States',
    SCL: 'Santiago, Chile',
    SEA: 'Seattle, WA, United States',
    SGN: 'Ho Chi Minh City, Vietnam',
    SHA: 'Shanghai, China',
    SIN: 'Singapore, Singapore',
    SJC: 'San Jose, CA, United States',
    SJO: 'San José, Costa Rica',
    SJW: 'Shijiazhuang, China',
    SKG: 'Thessaloniki, Greece',
    SLC: 'Salt Lake City, UT, United States',
    SMF: 'Sacramento, CA, United States',
    SOF: 'Sofia, Bulgaria',
    SSA: 'Salvador, Brazil',
    STL: 'St. Louis, MO, United States',
    SYD: 'Sydney, NSW, Australia',
    SZV: 'Suzhou, China',
    SZX: 'Dongguan, China',
    TBS: 'Tbilisi, Georgia',
    TGU: 'Tegucigalpa, Honduras',
    TLH: 'Tallahassee, FL, United States',
    TLL: 'Tallinn, Estonia',
    TLV: 'Tel Aviv, Israel',
    TNA: 'Jinan, China',
    TNR: 'Antananarivo, Madagascar',
    TPA: 'Tampa, FL, United States',
    TPE: 'Taipei',
    TSN: 'Tianjin, China',
    TXL: 'Berlin, Germany',
    UIO: 'Quito, Ecuador',
    ULN: 'Ulaanbaatar, Mongolia',
    VCP: 'Campinas, Brazil',
    VIE: 'Vienna, Austria',
    VNO: 'Vilnius, Lithuania',
    VTE: 'Vientiane, Laos',
    WAW: 'Warsaw, Poland',
    WUH: 'Wuhan, China',
    WUX: 'Wuxi, China',
    XIY: 'Xian, China',
    YUL: 'Montréal, QC, Canada',
    YVR: 'Vancouver, BC, Canada',
    YWG: 'Winnipeg, MB, Canada',
    YXE: 'Saskatoon, SK, Canada',
    YYC: 'Calgary, AB, Canada',
    YYZ: 'Toronto, ON, Canada',
    ZAG: 'Zagreb, Croatia',
    ZDM: 'Ramallah',
    ZRH: 'Zürich, Switzerland',
}