name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
       node-version: '12'
    - run: apt-fast update && apt-fast install -y jq
    - run: yarn install
    - run: yarn build
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
       apiToken: ${{ secrets.CF_API_TOKEN }}
       preCommands: |
          export KV_NAMESPACE_ID=$(npx @cloudflare/wrangler@1 kv:namespace list 2> >(tee stderr.log >&2) | head -1 | node -pe "JSON.parse(fs.readFileSync('/dev/stdin').toString()).find(kv => kv.title.includes('KV_STATUS_PAGE')).id")       postCommands: |

    env:
     CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
